name: Enviar Arquivo para Slack

on: [push]

jobs:
  send-file-to-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send file to Slack
        run: |
          if [ -f cypress/results/short.json ]; then
            FILE_CONTENT=$(jq -Rs '.' cypress/results/short.json)
          else
            FILE_CONTENT="Nenhum arquivo encontrado."
          fi
          curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$FILE_CONTENT\" }" $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}